name: CI/CD

on:
  workflow_dispatch:  # Запуск кнопкой "Run workflow"
  push:               # Запуск при новом коммите
  pull_request:
    branches:
      -main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest  # Среда выполнения — ВМ Ubuntu

    steps:
      - name: Клонирование кода репозитория на ВМ
        uses: actions/checkout@v4

      - name: Установка необходимых зависимостей
        run: sudo apt update && sudo apt install -y cmake g++ doxygen

      - name: Создание файлов сборки
        run: cmake .

      - name: Сборка
        run: cmake --build .

      - name: Запуск тестов
        run: ./tests

      - name: Генерация документации
        run: doxygen doxygen_file

      - name: Индентиыикация
        if: github.event_name == 'push'
        run: |
          git config --global user.email "a.galk.2019@yandex.ru"
          git config --global user.name "meentallyy"
          
      - name: Коммит изменений документации
        if: github.event_name == 'push'
        run: |
          git add docs/
          git commit -m "Автоматичесткое обновление документации"
          git push 